# Generated by Django 5.0.3 on 2024-03-13 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('imgs', models.ImageField(upload_to='Notification/')),
                ('content', models.TextField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.labels')),
            ],
        ),
    ]
